### ISSUE TITLE
Linking Interface to Python Scripts

### ISSUE THREAD

**Issue by c0d3ster** [njtrettel/SolverCAD#10]
The next high priority task item for the project is to link the python scripts to our UI and make the website fully functional.  The python scripts accept a file as input, so we'll probably have to put the FileObject back into text form.  We shouldn't need to add these scripts to the repo because we'll only need to host the site and run the scripts on one machine.   If we did put it into the repository, it may make deploying the site onto a VM easier if that's what Pete plans to do once the site is up and running.

**Comment by njtrettel** [comment]
`npm install python-shell`

**Comment by njtrettel** [comment]
Using `python-shell` to asynchronously call python scripts on a created temporary SCIN file (`runbuffer.scin`), and outputting to a temporary SCOUT file (`runbuffer.scout`). The server returns the contents of `runbuffer.scout`.
