### ISSUE TITLE
"Go Back" button

### ISSUE THREAD

**Issue by njtrettel** [njtrettel/SolverCAD#12]
The "Go Back" button on the `/FileEditor` route should send the user back to his most previous page. Right now it always sends the user back to `/FileStarter`.

**Comment by c0d3ster** [comment]
Hmm, I guess that is true.  We could store a last page in the UserStore that gets stored onEnter to /FileEditor or something along those lines.  I'm trying to get the Entry component worked out on the File Editor page so you can work on this one if you have time.

**Comment by njtrettel** [comment]
`browserHistory.goBack()`?
