### ISSUE TITLE
File Visibility Update Moving Forward

### ISSUE THREAD

**Issue by c0d3ster** [njtrettel/SolverCAD#15]
Just finished talking to Pete and tried to clarify what would be best moving forward as far as our file visibility settings goes... The first distinction that we need to make is between private and public files.  

1) private files - these files will go into the database under collection "userXfiles", can be named whatever the user would like (as long as it doesn't conflict with other "userXfiles" names), and can have as many generated functions as the user would like.  All functions created/used here will go to userX's functions in the "_users" collection.  If a user would like to push a private file to the "_publicfiles" collection, they may do so at any time without affecting the private version of the file (like a save as button... retains the old file but makes a new one too)

2) public files - these files will go into the database under collection "_publicfiles" and can be edited by ANYONE.  They would still always be attached to the user who created the file, but anyone could make changes to a public file.  They can also still have as many generated functions as desired.  This is different from what we were previously thinking, but I think the idea is that eventually we will have version control and permissions for files to refine this "public" idea.  We're thinking about refactoring "public" to "collaborative", "team", or some other better term to describe openly accessible and editable files.  I was thinking that anyone who edits a public file would pull in the functions to their user functions field in the "_users" collection, but I'm not sure if that's the best way to go about the python code generation or not.

The second concept is that of PUBLISHED files.  These files are ones that are complete and verified to work properly with exactly 1 function attached.  The FILES should be viewable by everyone (along with their function being in the publiclibrary.py) but editable by no one.  Anyone can import in a published file to their private files collection, but they must rename it if they want to republish it.  Files can be published from either public or private visibility.

We will discuss all of this again upon your return Friday as these definitions are not set in stone, but I'd just like to have them written down somewhere so we can be on the same page moving forward.

**Comment by njtrettel** [comment]
We need a way to differentiate between getting/saving file data from the `_publicfiles` collection and the `[user]files` collection

**Comment by njtrettel** [comment]
@c0d3ster when we render a `FileContainer` we pass in either `true` or `false` for a prop called `public`, which determines the click listener it will fire when "Open" is clicked. If it is public, it pulls from the `_publicfiles` collection, `[user]files` otherwise.  These click listeners lead to the FileStore either setting its `isPublic` field to true or false. This allows the "Save" button to save to the correct database. 

We do not handle version control as of now.
