### ISSUE TITLE
publicFiles, myFiles, and currFile

### ISSUE THREAD

**Issue by c0d3ster** [njtrettel/SolverCAD#6]
The next goal for this project is to distinguish between: 
1. publicFiles (grabs all files with public field set to 1)
2.  myFiles (grabs all files with name == currUser.name)
3. currFile (grabs data for current file being edited)

This will require adjust data flow for the three following locations:
1. FileStore.jsx
2. FileActions.jsx
3. server.js

This will also require editing the Upload, EditFile, PublicFiles, and Files components to fetch and display the correct data.

**Comment by njtrettel** [comment]
This presents a good reason to add the authentication in the header. The next step after this is authenticating our server enpoints @c0d3ster
